"""
Interactive JDK installer.

Asks everything it needs up front (DB connection, clean vs. upgrade,
secrets, optional first admin account), writes .env, then detaches the
actual work into a background process so closing this terminal / SSH
session does not kill the install. Progress is written to
backend/install.log.

Usage (from backend/, with the virtualenv active):

    python scripts/install.py
    python scripts/install.py --no-detach   # run in the foreground instead
"""
import argparse
import getpass
import json
import os
import secrets
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

# See the matching comment in init_db.py: redirected stdout on Windows can
# fall back to a codepage that can't encode non-ASCII output.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

BACKEND_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BACKEND_DIR.parent
ENV_PATH = REPO_ROOT / ".env"
ENV_EXAMPLE_PATH = REPO_ROOT / ".env.example"
LOG_PATH = BACKEND_DIR / "install.log"

sys.path.insert(0, str(BACKEND_DIR))


def _parse_env(path: Path) -> dict:
    values = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = val.strip()
    return values


def _prompt(label: str, default: str = "", secret: bool = False) -> str:
    suffix = f" [{default}]" if default and not secret else (" [hidden]" if secret and default else "")
    reader = getpass.getpass if secret else input
    raw = reader(f"{label}{suffix}: ")
    return raw.strip() or default


def _yes_no(label: str, default: bool = False) -> bool:
    hint = "Y/n" if default else "y/N"
    raw = input(f"{label} ({hint}): ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _gather_interactively() -> dict:
    print("=== JDK interactive installer ===\n")
    existing = _parse_env(ENV_PATH)
    example = _parse_env(ENV_EXAMPLE_PATH)

    print("-- Database connection --")
    db_host = _prompt("DB host", existing.get("DB_HOST", example.get("DB_HOST", "localhost")))
    db_port = _prompt("DB port", existing.get("DB_PORT", example.get("DB_PORT", "3306")))
    db_user = _prompt("DB user", existing.get("DB_USER", example.get("DB_USER", "root")))
    db_password = _prompt("DB password", existing.get("DB_PASSWORD", ""), secret=True)
    db_name = _prompt("DB name", existing.get("DB_NAME", example.get("DB_NAME", "jdk")))

    print()
    clean = _yes_no(
        "Clean install? This DROPS the existing database and rebuilds it from scratch",
        default=False,
    )

    print("\n-- Secrets --")
    auth_secret = existing.get("AUTH_SIGNING_SECRET", "")
    if not auth_secret or clean:
        auth_secret = secrets.token_urlsafe(48)
        print("Generated a new AUTH_SIGNING_SECRET.")
    files_secret = existing.get("FILES_SIGNING_SECRET", "")
    if not files_secret or clean:
        files_secret = secrets.token_urlsafe(48)
        print("Generated a new FILES_SIGNING_SECRET.")

    print("\n-- Application --")
    environment = _prompt("Environment", existing.get("ENVIRONMENT", "development"))
    cors_origins = _prompt("CORS origins (comma-separated)", existing.get("CORS_ORIGINS", "http://localhost:5173"))
    require_email_verification = _prompt(
        "Require email verification (true/false)",
        existing.get("REQUIRE_EMAIL_VERIFICATION", "true"),
    )
    files_storage_path = _prompt("Files storage path", existing.get("FILES_STORAGE_PATH", "./var/files"))
    files_max_upload = _prompt("Max upload size (bytes)", existing.get("FILES_MAX_UPLOAD_SIZE", "52428800"))

    print("\n-- First administrator account --")
    create_admin = _yes_no("Create an administrator account now?", default=True)
    admin = {}
    if create_admin:
        admin["email"] = _prompt("Admin email", existing.get("DEFAULT_ADMIN_EMAIL", "admin@jdk.local"))
        while True:
            pw1 = _prompt("Admin password", secret=True)
            if len(pw1) < 8:
                print("Password must be at least 8 characters.")
                continue
            pw2 = _prompt("Confirm admin password", secret=True)
            if pw1 != pw2:
                print("Passwords do not match, try again.")
                continue
            admin["password"] = pw1
            break
        admin["full_name"] = _prompt("Admin full name", "Administrator")

    print("\n-- Summary --")
    print(f"  DB:          {db_user}@{db_host}:{db_port}/{db_name}")
    print(f"  Clean install: {clean}")
    print(f"  Create admin:  {create_admin}")
    if not _yes_no("Proceed?", default=True):
        print("Aborted.")
        sys.exit(1)

    env_lines = [
        "# Generated by scripts/install.py",
        "",
        "# --- Shared MySQL database ---",
        f"DB_HOST={db_host}",
        f"DB_PORT={db_port}",
        f"DB_USER={db_user}",
        f"DB_PASSWORD={db_password}",
        f"DB_NAME={db_name}",
        "",
        "# --- perennia-auth ---",
        f"AUTH_SIGNING_SECRET={auth_secret}",
        f"REQUIRE_EMAIL_VERIFICATION={require_email_verification}",
        "",
        "# --- perennia-files ---",
        f"FILES_SIGNING_SECRET={files_secret}",
        f"FILES_STORAGE_PATH={files_storage_path}",
        f"FILES_MAX_UPLOAD_SIZE={files_max_upload}",
        "",
        "# --- Application ---",
        f"ENVIRONMENT={environment}",
        f"CORS_ORIGINS={cors_origins}",
        f"DEFAULT_ADMIN_EMAIL={admin.get('email', existing.get('DEFAULT_ADMIN_EMAIL', 'admin@jdk.local'))}",
        "DEFAULT_ADMIN_PASSWORD=",
        "",
    ]
    if ENV_PATH.exists():
        backup = ENV_PATH.with_suffix(".env.bak")
        ENV_PATH.replace(backup)
        print(f"Existing .env backed up to {backup.name}")
    ENV_PATH.write_text("\n".join(env_lines), encoding="utf-8")
    os.chmod(ENV_PATH, 0o600)
    print(f".env written to {ENV_PATH}")

    return {"clean": clean, "create_admin": create_admin, "admin": admin}


def _run_install(answers: dict) -> None:
    """The actual (potentially slow) work. Runs either in-process (--no-detach)
    or as the detached child."""
    import init_db
    import create_admin as create_admin_mod

    init_db.run(clean=answers["clean"])

    if answers.get("create_admin"):
        admin = answers["admin"]
        create_admin_mod.run(admin["email"], admin["password"], admin["full_name"])

    print("\nINSTALL COMPLETE")


def _detach(answers: dict) -> None:
    fd, answers_path = tempfile.mkstemp(prefix="jdk-install-", suffix=".json", dir=str(BACKEND_DIR))
    os.close(fd)
    os.chmod(answers_path, 0o600)
    Path(answers_path).write_text(json.dumps(answers), encoding="utf-8")

    args = [sys.executable, str(Path(__file__).resolve()), "--run-detached", "--answers", answers_path]
    log_f = open(LOG_PATH, "ab", buffering=0)
    log_f.write(f"\n=== install started {os.getpid()} ===\n".encode())

    if os.name == "nt":
        DETACHED_PROCESS = 0x00000008
        CREATE_NEW_PROCESS_GROUP = 0x00000200
        proc = subprocess.Popen(
            args, stdout=log_f, stderr=log_f, stdin=subprocess.DEVNULL,
            creationflags=DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP,
            close_fds=True, cwd=str(BACKEND_DIR),
        )
    else:
        proc = subprocess.Popen(
            args, stdout=log_f, stderr=log_f, stdin=subprocess.DEVNULL,
            start_new_session=True, close_fds=True, cwd=str(BACKEND_DIR),
        )

    print(f"\nInstalling in the background (PID {proc.pid}).")
    print(f"It will keep running even if you close this terminal.")
    print(f"Progress log: {LOG_PATH}")
    if os.name == "nt":
        print(f"Tail it:  Get-Content -Path '{LOG_PATH}' -Wait -Tail 50")
    else:
        print(f"Tail it:  tail -f '{LOG_PATH}'")


def main() -> None:
    parser = argparse.ArgumentParser(description="Interactive JDK installer.")
    parser.add_argument("--no-detach", action="store_true", help="Run the install in the foreground instead.")
    parser.add_argument("--run-detached", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--answers", help=argparse.SUPPRESS)
    args = parser.parse_args()

    if args.run_detached:
        answers_path = Path(args.answers)
        try:
            answers = json.loads(answers_path.read_text(encoding="utf-8"))
        finally:
            answers_path.unlink(missing_ok=True)
        try:
            _run_install(answers)
        except Exception:
            print("INSTALL FAILED")
            traceback.print_exc()
            sys.exit(1)
        return

    answers = _gather_interactively()

    if args.no_detach:
        _run_install(answers)
    else:
        _detach(answers)


if __name__ == "__main__":
    main()
